### PR TITLE
Try to Rewrite Animation

### PR DESCRIPTION
**Pull request by HEKEPOIU**

### CODE REVIEW

**Review by NOOBDY — CHANGES_REQUESTED** [review]
I think the looping cooldown is not doing anything

**Comment by HEKEPOIU** [comment]
Following Function should be work:
1. Play and Pause.
2. Cooldown when ```m_looping == true``` & animate end.
3. Change Animate Speed ```SetInterval()```, you can press ```k``` to test.
4. Looping toggle.
5. ```STATE::ENDED``` When ```m_looping == false``` & animate end.

**Review by ntut-rick — COMMENTED** [review]
IWOMM

**Comment by HEKEPOIU** [comment]
This push may fix #131?
(depend on my reading skill...)
how to test:
(please set ```DEFAULT_LOG_LEVEL = Util::Logger::Level::TRACE```)
1. pause animate( press ```A``` )
2. Set Animate Visible to ```false``` ( press ```B``` )
3. play animate ( press ```S``` )
4. Wait 10s ( as long as you want )
5. Set Animate Visible to ```true``` ( press```V``` )
6. see the log trace if right? (the log should be continue number(currentframe) after Set the Visible to true).

**Review by NOOBDY — CHANGES_REQUESTED** [review]
I think calling `Pause()` during cooldown does nothing

**Review by NOOBDY — DISMISSED** [review]

**Review by NOOBDY — APPROVED** [review]

**Pull request merged**
