### PR TITLE
fix workflow condition

### PR DESCRIPTION
**Pull request by NOOBDY**
I discovered due to a typo we never ran `clang-format` and `clang-tidy` checks

### CODE REVIEW

**Comment by ntut-rick** [comment]
https://github.com/ZedThree/clang-tidy-review looks cool

**Comment by ntut-rick** [comment]
> IDK if this works. How do i test it?

I think it's failed

**Comment by NOOBDY** [comment]
current the `post` workflow couldn't be run due to [GitHub limitations](https://github.com/orgs/community/discussions/25288#discussioncomment-3247293)

**Review by ntut-rick — APPROVED** [review]
It Work On Github's machine 🎉

**Comment by Dragonfly911117** [comment]
IDK if this works. How do i test it?

**Comment by NOOBDY** [comment]
i think you just need to see the action results

**Comment by Dragonfly911117** [comment]
> i think you just need to see the action results

U mean this? ```shLine filter for clang-tidy:
[{"name":"src/App.cpp","lines":[[42,42],[53,54]]},{"name":"test/Interactive/Audio.cpp","lines":[[9,9],[56,61]]},{"name":"test/TransformTest.cpp","lines":[[12,12]]}]

Using config: --checks=-*,performance-*,readability-*,bugprone-*,clang-analyzer-*,cppcoreguidelines-*,mpi-*,misc-*
Running:


clang-tidy failed with return code 1 and error:
57943 warnings and 2 errors generated.
Error while processing /github/workspace/include/Util/Input.hpp.
79809 warnings and 3 errors generated.
Error while processing /github/workspace/include/pch.hpp.
144040 warnings and 5 errors generated.
Error while processing /github/workspace/src/App.cpp.
208271 warnings and 7 errors generated.
Error while processing /github/workspace/src/App.cpp.
272502 warnings and 9 errors generated.
Error while processing /github/workspace/src/App.cpp.
347592 warnings and 11 errors generated.
Error while processing /github/workspace/test/Interactive/Audio.cpp.
393487 warnings and 11 errors generated.
Error while processing /github/workspace/test/TransformTest.cpp.
Suppressed 393558 warnings (393431 in non-user code, 56 due to line filter, 71 NOLINT).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
Found compiler error(s).
```

**Comment by NOOBDY** [comment]
i mean it wasn't running at all before so probably yes

**Review by Dragonfly911117 — APPROVED** [review]

**Pull request merged**
